### PR TITLE
test PR 1

### PR DESCRIPTION
**Pull request by gnanaajana-govindaraju**

### CODE REVIEW

**Comment by gnanaajana-govindaraju** [comment]
#### Widget Performance measurement:
Widget Measurement Report is taken using lighthouse
| Measurement | Time (seconds) |
| :--- |  :---: | 
| First Contentful Paint | 0.80 | 
| First Meaningful Paint | 0.90 | 
| First CPU Idle | 1.23 | 
| Time to Interactive | 1.23 | 
| Speed Index | 1.65 | 
| Max Potential First Input Delay | 0.06 | 
| Total Blocking Time | 0.01 | 
| Estimated Input Latency | 0.02 | 
| JavaScript execution time | 0.23 | 
#### Total Weights:
| URL | Size |
| :--- |  :---: | 
| [https://widget.freshworks.com/widgetBase/widget.js](https://widget.freshworks.com/widgetBase/widget.js) | 93.43 KB | 
| [https://widget.freshworks.com/widgetBase/8.7a1aae861d040e04ce42.widget.js](https://widget.freshworks.com/widgetBase/8.7a1aae861d040e04ce42.widget.js) | 11.57 KB | 
| [https://widget.freshworks.com/widgetBase/7.6529bade575b76185b69.widget.js](https://widget.freshworks.com/widgetBase/7.6529bade575b76185b69.widget.js) | 11.23 KB | 
| [https://widget.freshworks.com/widgetBase/0.b5180f41fb3e42f3108a.widget.js](https://widget.freshworks.com/widgetBase/0.b5180f41fb3e42f3108a.widget.js) | 7.52 KB | 
| [https://widget.freshworks.com/widgetBase/bootstrap.js](https://widget.freshworks.com/widgetBase/bootstrap.js) | 3.24 KB | 
| [https://widget.freshworks.com/widgetBase/locales/en.json](https://widget.freshworks.com/widgetBase/locales/en.json) | 2.01 KB | 
| [https://widget.freshworks.com/widgets/11000000091.json?randomId=0.027804543226076284](https://widget.freshworks.com/widgets/11000000091.json?randomId=0.027804543226076284) | 1.03 KB | 
| [https://widget.freshworks.com/widgetBase/15.7f3178cd0b9f72af656c.widget.js](https://widget.freshworks.com/widgetBase/15.7f3178cd0b9f72af656c.widget.js) | 943 Bytes | 
| [http://helpwdiegt-performance.surge.sh/](http://helpwdiegt-performance.surge.sh/) | 888 Bytes | 
| [https://widget.freshworks.com/widgetBase/static/media/frame.e3b386c1.css](https://widget.freshworks.com/widgetBase/static/media/frame.e3b386c1.css) | 758 Bytes |

**Comment by gnanaajana-govindaraju** [comment]
#### Widget Performance measurement:
Widget Measurement Report is taken using lighthouse
| Measurement | Time (seconds) |
| :--- |  :---: | 
| First Contentful Paint | 0.76 | 
| First Meaningful Paint | 0.76 | 
| First CPU Idle | 0.76 | 
| Time to Interactive | 0.76 | 
| Speed Index | 0.76 | 
| Max Potential First Input Delay | 0.02 | 
| Total Blocking Time | 0.00 | 
| Estimated Input Latency | 0.02 | 
| JavaScript execution time | 0.00 |

**Comment by gnanaajana-govindaraju** [comment]
#### Widget Performance measurement:
Widget Measurement Report is taken using lighthouse
| Measurement | Time (seconds) |
| :--- |  :---: | 
| First Contentful Paint | 0.96 | 
| First Meaningful Paint | 0.96 | 
| First CPU Idle | 0.96 | 
| Time to Interactive | 0.96 | 
| Speed Index | 0.97 | 
| Max Potential First Input Delay | 0.03 | 
| Total Blocking Time | 0.00 | 
| Estimated Input Latency | 0.02 | 
| JavaScript execution time | 0.04 |

**Comment by gnanaajana-govindaraju** [comment]
#### Widget Performance measurement:
Widget Measurement Report is taken using lighthouse
| Measurement | Time (seconds) |
| :--- |  :---: | 
| First Contentful Paint | 0.85 | 
| First Meaningful Paint | 0.85 | 
| First CPU Idle | 0.85 | 
| Time to Interactive | 0.85 | 
| Speed Index | 0.86 | 
| Max Potential First Input Delay | 0.02 | 
| Total Blocking Time | 0.00 | 
| Estimated Input Latency | 0.02 | 
| JavaScript execution time | 0.01 |

**Comment by gnanaajana-govindaraju** [comment]
#### Widget Performance measurement:
Widget Measurement Report is taken using lighthouse
| Measurement | Time (seconds) |
| :--- |  :---: | 
| First Contentful Paint | 0.89 | 
| First Meaningful Paint | 0.89 | 
| First CPU Idle | 0.89 | 
| Time to Interactive | 0.89 | 
| Speed Index | 0.89 | 
| Max Potential First Input Delay | 0.02 | 
| Total Blocking Time | 0.00 | 
| Estimated Input Latency | 0.02 | 
| JavaScript execution time | 0.01 |

**Comment by prakash-chokalingam** [comment]
Rejected

**Comment by gnanaajana-govindaraju** [comment]
#### Widget Performance measurement:
Widget Measurement Report is taken using lighthouse
| Measurement | Time (seconds) |
| :--- |  :---: | 
| First Contentful Paint | 0.87 | 
| First Meaningful Paint | 0.87 | 
| First CPU Idle | 0.87 | 
| Time to Interactive | 0.87 | 
| Speed Index | 0.87 | 
| Max Potential First Input Delay | 0.02 | 
| Total Blocking Time | 0.00 | 
| Estimated Input Latency | 0.02 | 
| JavaScript execution time | 0.01 |

**Pull request merged**
